### ISSUE TITLE
AttributeError: 'Book' object has no attribute 'extract_formulas'

### ISSUE THREAD

**Issue by FabZ90** [chris1610/pbpython#14]
Using:
Pycharm 2018.2.4
Python 3.6

Just want to copy and run the code, but this is what I get:

Traceback (most recent call last):
  File "C:/Users/Fabian/PycharmProjects/Thesis/stacked_bar_app.py", line 8, in <module>
    "https://github.com/chris1610/pbpython/blob/master/data/salesfunnel.xlsx?raw=True"
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\util\_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\io\excel.py", line 230, in read_excel
    io = ExcelFile(io, engine=engine)
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\io\excel.py", line 292, in __init__
    self.book = xlrd.open_workbook(file_contents=data)
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlrd\__init__.py", line 141, in open_workbook
    ragged_rows=ragged_rows,
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlrd\xlsx.py", line 808, in open_workbook_2007_xml
    x12book.process_stream(zflo, 'Workbook')
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlrd\xlsx.py", line 265, in process_stream
    meth(self, elem)
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlrd\xlsx.py", line 392, in do_sheet
    sheet = Sheet(bk, position=None, name=name, number=sheetx)
  File "C:\Users\Fabian\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlrd\sheet.py", line 326, in __init__
    self.extract_formulas = book.extract_formulas
AttributeError: 'Book' object has no attribute 'extract_formulas'

Does anyone can help?
Thanks!

**Comment by ghost** [comment]
yes >..
![Screenshot 2021-08-23 222305](https://user-images.githubusercontent.com/89059097/130490272-8adc869e-6926-459d-926f-421a598011eb.jpg)

**Comment by chris1610** [comment]
The error is within xlrd. I would recommend updating the version of xlrd or installing openpyxl. That should fix the issue.
